### Obtener todos los alumnos
GET http://localhost:8080/api/v1/alumnos
Authorization: Bearer ya29.a0AeDClZBWErj9D_dMEaNVQIqd3h8ES9Qf31dQzQgF9iwavTJZvIv3YV6gCTNzFnUQ2hQM5Tx4eUes7GA260rPC0yj4qemMVIdDWCYxSwI06oxZ1oKRWNesR0YGtws0-Ljz6EGsLrT7KdWVRQJteDrRg4wfYty1J_3WcgHNQLBaCgYKAS4SARESFQHGX2MiS7NTvYo--bop4b7izAPuuw0175


### Obtener un alumno por id
GET http://localhost:8080/api/v1/alumnos/3
Authorization: Bearer ya29.a0AeDClZBWErj9D_dMEaNVQIqd3h8ES9Qf31dQzQgF9iwavTJZvIv3YV6gCTNzFnUQ2hQM5Tx4eUes7GA260rPC0yj4qemMVIdDWCYxSwI06oxZ1oKRWNesR0YGtws0-Ljz6EGsLrT7KdWVRQJteDrRg4wfYty1J_3WcgHNQLBaCgYKAS4SARESFQHGX2MiS7NTvYo--bop4b7izAPuuw0175


### Crear un nuevo alumno
POST http://localhost:8080/api/v1/alumnos
Authorization: Bearer ya29.a0AeDClZBWErj9D_dMEaNVQIqd3h8ES9Qf31dQzQgF9iwavTJZvIv3YV6gCTNzFnUQ2hQM5Tx4eUes7GA260rPC0yj4qemMVIdDWCYxSwI06oxZ1oKRWNesR0YGtws0-Ljz6EGsLrT7KdWVRQJteDrRg4wfYty1J_3WcgHNQLBaCgYKAS4SARESFQHGX2MiS7NTvYo--bop4b7izAPuuw0175
Content-Type: application/json

{
  "semestre": 5,
  "materiasAprobadas": 10,
  "puntaje": 85.5,
  "idPersona": 5
}


### Actualizar un alumno existente
PUT http://localhost:8080/api/v1/alumnos/3
Authorization: Bearer ya29.a0AeDClZBWErj9D_dMEaNVQIqd3h8ES9Qf31dQzQgF9iwavTJZvIv3YV6gCTNzFnUQ2hQM5Tx4eUes7GA260rPC0yj4qemMVIdDWCYxSwI06oxZ1oKRWNesR0YGtws0-Ljz6EGsLrT7KdWVRQJteDrRg4wfYty1J_3WcgHNQLBaCgYKAS4SARESFQHGX2MiS7NTvYo--bop4b7izAPuuw0175
Content-Type: application/json

{
  "semestre": 7,
  "materiasAprobadas": 25,
  "puntaje": 90.0
}


### Eliminar un alumno (borrado lógico) // success: 204
DELETE http://localhost:8080/api/v1/alumnos/3
Authorization: Bearer ya29.a0AeDClZBWErj9D_dMEaNVQIqd3h8ES9Qf31dQzQgF9iwavTJZvIv3YV6gCTNzFnUQ2hQM5Tx4eUes7GA260rPC0yj4qemMVIdDWCYxSwI06oxZ1oKRWNesR0YGtws0-Ljz6EGsLrT7KdWVRQJteDrRg4wfYty1J_3WcgHNQLBaCgYKAS4SARESFQHGX2MiS7NTvYo--bop4b7izAPuuw0175
