### Obtener todos los comentarios de un foro
GET http://localhost:8080/api/v1/comentarios/foro/2
Authorization: Bearer ya29.a0AeDClZCsQJnIPG4JoU3CKgQsjtJ9Vw64hOZWgq7YdWDkxS-eX85jPegB5uih5FcXaPB9Lryq4JCVpJ7GnSUcBczTeBTExFx_TxcQrnJrOMdphQVUH9hW_WuPZVpz-ZRfFlsXh-rAYy_5X43thIqDoE6OMj-kXlyYhGgaCgYKAbYSARESFQHGX2MiP8THGe1SO0jG_PVrCMUEug0170


### Obtener un comentario por id
GET http://localhost:8080/api/v1/comentarios/3
Authorization: Bearer ya29.a0AeDClZCsQJnIPG4JoU3CKgQsjtJ9Vw64hOZWgq7YdWDkxS-eX85jPegB5uih5FcXaPB9Lryq4JCVpJ7GnSUcBczTeBTExFx_TxcQrnJrOMdphQVUH9hW_WuPZVpz-ZRfFlsXh-rAYy_5X43thIqDoE6OMj-kXlyYhGgaCgYKAbYSARESFQHGX2MiP8THGe1SO0jG_PVrCMUEug0170


### Crear un nuevo comentario
POST http://localhost:8080/api/v1/comentarios
Authorization: Bearer ya29.a0AeDClZCsQJnIPG4JoU3CKgQsjtJ9Vw64hOZWgq7YdWDkxS-eX85jPegB5uih5FcXaPB9Lryq4JCVpJ7GnSUcBczTeBTExFx_TxcQrnJrOMdphQVUH9hW_WuPZVpz-ZRfFlsXh-rAYy_5X43thIqDoE6OMj-kXlyYhGgaCgYKAbYSARESFQHGX2MiP8THGe1SO0jG_PVrCMUEug0170
Content-Type: application/json

{
  "texto": "Excelente foro, me encanta.",
  "fechaHora": "2024-11-25T00:00:00",
  "idForo": 2,
  "idUsuario": 2
}


### Actualizar un comentario existente
PUT http://localhost:8080/api/v1/comentarios/3
Authorization: Bearer ya29.a0AeDClZCsQJnIPG4JoU3CKgQsjtJ9Vw64hOZWgq7YdWDkxS-eX85jPegB5uih5FcXaPB9Lryq4JCVpJ7GnSUcBczTeBTExFx_TxcQrnJrOMdphQVUH9hW_WuPZVpz-ZRfFlsXh-rAYy_5X43thIqDoE6OMj-kXlyYhGgaCgYKAbYSARESFQHGX2MiP8THGe1SO0jG_PVrCMUEug0170
Content-Type: application/json

{
  "texto": "Excelente foro, me encanta. Me gustaría que se agregue más información sobre marketing digital.",
  "fechaHora": "2024-11-25T01:00:00"
}


### Eliminar un comentario (borrado lógico) // success: 204
DELETE http://localhost:8080/api/v1/comentarios/3
Authorization: Bearer ya29.a0AeDClZCsQJnIPG4JoU3CKgQsjtJ9Vw64hOZWgq7YdWDkxS-eX85jPegB5uih5FcXaPB9Lryq4JCVpJ7GnSUcBczTeBTExFx_TxcQrnJrOMdphQVUH9hW_WuPZVpz-ZRfFlsXh-rAYy_5X43thIqDoE6OMj-kXlyYhGgaCgYKAbYSARESFQHGX2MiP8THGe1SO0jG_PVrCMUEug0170
