### Registrar un documento leído y otorgar una medalla
POST http://localhost:8080/api/v1/documentos-leidos
Authorization: Bearer ya29.a0AeDClZCTVAVQoO1bAo-r-zyXPFuuAXep9TjL94Eusl-JgG1GHs3mh68tM_bwlxKxnBAfC0R42cNGoBSGmgs8LMQdOMRtarrmg6NyBOlCsueOiOn-w5hf80E8vcDhTJJiTMUJTVwY7t9ftHPAXMFaiaWLka5iY_yaBqwaCgYKAdQSARESFQHGX2MiuT4Cn3s0a30O24qOePo4eQ0170
Content-Type: application/json

{
  "fecha": "2024-11-25",
  "idDocumento": 1,
  "idAlumno": 2
}


### Obtener todos los documentos leídos por un alumno
GET http://localhost:8080/api/v1/documentos-leidos/alumno/2
Authorization: Bearer ya29.a0AeDClZCTVAVQoO1bAo-r-zyXPFuuAXep9TjL94Eusl-JgG1GHs3mh68tM_bwlxKxnBAfC0R42cNGoBSGmgs8LMQdOMRtarrmg6NyBOlCsueOiOn-w5hf80E8vcDhTJJiTMUJTVwY7t9ftHPAXMFaiaWLka5iY_yaBqwaCgYKAdQSARESFQHGX2MiuT4Cn3s0a30O24qOePo4eQ0170


### Obtener todas las medallas ganadas por un alumno
GET http://localhost:8080/api/v1/documentos-leidos/medallas/alumno/2
Authorization: Bearer ya29.a0AeDClZCTVAVQoO1bAo-r-zyXPFuuAXep9TjL94Eusl-JgG1GHs3mh68tM_bwlxKxnBAfC0R42cNGoBSGmgs8LMQdOMRtarrmg6NyBOlCsueOiOn-w5hf80E8vcDhTJJiTMUJTVwY7t9ftHPAXMFaiaWLka5iY_yaBqwaCgYKAdQSARESFQHGX2MiuT4Cn3s0a30O24qOePo4eQ0170
